import type { PropertyData } from "@src/types/property";

export const mockProperties: PropertyData[] = [
	{
		id: "1",
		title: "Moderno departamento en Palermo",
		propertyType: "apartment",
		status: "available",
		address: "Av. Santa Fe 2456",
		city: "Palermo",
		province: "Buenos Aires",
		postalCode: "C1425",
		assignedOwner: "Juan Pérez",
		rooms: 4,
		floors: 1,
		bedrooms: 2,
		age: 5,
		bathrooms: 3,
		toilets: 0,
		garages: 0,
		price: 125000,
		expenses: 15000,
		currency: "usd",
	},
	{
		id: "2",
		title: "Casa en Belgrano con jardín",
		propertyType: "house",
		status: "available",
		address: "Juramento 3145",
		city: "Belgrano",
		province: "Buenos Aires",
		postalCode: "C1428",
		assignedOwner: "María González",
		rooms: 4,
		floors: 2,
		bedrooms: 3,
		age: 10,
		bathrooms: 2,
		toilets: 1,
		garages: 2,
		price: 350000,
		expenses: 25000,
		currency: "usd",
	},
	{
		id: "3",
		title: "Loft en Recoleta",
		propertyType: "apartment",
		status: "available",
		address: "Av. Callao 1234",
		city: "Recoleta",
		province: "Buenos Aires",
		postalCode: "C1023",
		assignedOwner: "Carlos Martínez",
		rooms: 2,
		floors: 1,
		bedrooms: 1,
		age: 2,
		bathrooms: 1,
		toilets: 0,
		garages: 0,
		price: 180000,
		expenses: 18000,
		currency: "usd",
	},
	{
		id: "4",
		title: "Departamento con vista al río",
		propertyType: "apartment",
		status: "reserved",
		address: "Av. del Libertador 5678",
		city: "Núñez",
		province: "Buenos Aires",
		postalCode: "C1429",
		assignedOwner: "Ana Rodríguez",
		rooms: 4,
		floors: 1,
		bedrooms: 3,
		age: 8,
		bathrooms: 2,
		toilets: 1,
		garages: 1,
		price: 280000,
		expenses: 22000,
		currency: "usd",
	},
	{
		id: "5",
		title: "Monoambiente en Caballito",
		propertyType: "apartment",
		status: "available",
		address: "Av. Rivadavia 6789",
		city: "Caballito",
		province: "Buenos Aires",
		postalCode: "C1406",
		assignedOwner: "Pedro López",
		rooms: 1,
		floors: 1,
		bedrooms: 1,
		age: 15,
		bathrooms: 1,
		toilets: 0,
		garages: 0,
		price: 65000,
		expenses: 8000,
		currency: "usd",
	},
	{
		id: "6",
		title: "Penthouse en Puerto Madero",
		propertyType: "ph",
		status: "available",
		address: "Juana Manso 1200",
		city: "Puerto Madero",
		province: "Buenos Aires",
		postalCode: "C1107",
		assignedOwner: "Roberto Fernández",
		rooms: 5,
		floors: 2,
		bedrooms: 4,
		age: 3,
		bathrooms: 3,
		toilets: 2,
		garages: 3,
		price: 580000,
		expenses: 45000,
		currency: "usd",
	},
	{
		id: "7",
		title: "Departamento en Villa Urquiza",
		propertyType: "apartment",
		status: "available",
		address: "Triunvirato 4567",
		city: "Villa Urquiza",
		province: "Buenos Aires",
		postalCode: "C1431",
		assignedOwner: "Laura Sánchez",
		rooms: 2,
		floors: 1,
		bedrooms: 1,
		age: 12,
		bathrooms: 1,
		toilets: 0,
		garages: 0,
		price: 95000,
		expenses: 10000,
		currency: "usd",
	},
	{
		id: "8",
		title: "Casa quinta en San Isidro",
		propertyType: "house",
		status: "available",
		address: "Av. Centenario 890",
		city: "San Isidro",
		province: "Buenos Aires",
		postalCode: "B1642",
		assignedOwner: "Diego Torres",
		rooms: 6,
		floors: 2,
		bedrooms: 5,
		age: 20,
		bathrooms: 3,
		toilets: 2,
		garages: 4,
		price: 450000,
		expenses: 30000,
		currency: "usd",
	},
];
